### ISSUE TITLE
Admin Privilege required Error

### ISSUE THREAD

**Issue by bivinvinod** [calebporzio/simple-php-cs-fixer#2]
> Run VS Code with admin privileges so the changes can be applied.

 error is shown when i try to run. 

> spawn php-cs-fixer ENOENT: Error: spawn php-cs-fixer ENOENT
> 	at exports._errnoException (util.js:1050:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 	at onErrorNT (internal/child_process.js:367:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 	at process._tickCallback (internal/process/next_tick.js:104:9)
> 
> e.onUnexpectedError | @ | /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29_

**Comment by calebporzio** [comment]
Where is that error shown?

**Comment by bivinvinod** [comment]
This popup is shown when i try to run simple php cs fixer. 
![screenshot from 2017-11-01 13-00-11](https://user-images.githubusercontent.com/6111496/32264433-a8b857e0-bf04-11e7-963c-3a16f6639f29.png)

The other error message that i posted is from the developer option console.
I think there is some clash with Custom css and js loader plugin. The alert has gone when i disabled it. hmm..

**Comment by calebporzio** [comment]
Hmm... it seems to have to do with node's child process `spawn` method. 

Did you try running VS Code "as administrator"? Also, I'm assuming you're on windows?

But either way, this is odd - are you still having the issue with Custom css loader plugin?
