### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by ben182** [calebporzio/simple-php-cs-fixer#6]
Hey,

I get this error when I want to fix a file
`  ERR spawn php-cs-fixer ENOENT: Error: spawn php-cs-fixer ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

I am on windows

**Comment by janpio** [comment]
I am getting the same error:
```
ERR spawn php-cs-fixer ENOENT: Error: spawn php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```
Did you ever fix this?
Starting to investigate now myself.

**Comment by janpio** [comment]
Running `php-cs-fixer` in the project folder in the command line works, I also removed all configuration I already created to see if this changes anything - it doesn't.

**Comment by janpio** [comment]
Runnign VS Code as admin didn't change anything (inspired by #2).
