### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by faizanakram99** [calebporzio/simple-php-cs-fixer#9]
It doesn't seem to work, I have php-cs-fixer globally installed and .php_cs.dist also exists in project dir, simple-php-cs-fixer.save is true, still php-cs-fixer is never fired, tried to run it manually from command palette it does nothing, nothing at all.

I also have composer command set up for running php-cs-fixer and it just seems fine. Also i have added php-cs-fixer in PhpStorm as a file watcher for PHP files, there also it seems fine.

So there is indeed some issue with extension and my php-cs-fixer installation

**Comment by calebporzio** [comment]
Are you still experiencing this issue?

I have the following configuration and everything is working great:
```
    "simple-php-cs-fixer.useConfig": true,
    "simple-php-cs-fixer.config": ".php_cs.dist",
    "simple-php-cs-fixer.save": true,
```

**Comment by edalzell** [comment]
and where is that file @calebporzio, and what does that `php_cs.dist` file look like?

**Comment by edalzell** [comment]
ya I get this with those settings: 
<img width="957" alt="image" src="https://user-images.githubusercontent.com/6069653/75493232-4826d300-596e-11ea-950b-fd4bbf33a2a0.png">

**Comment by faizanakram99** [comment]
@calebporzio
Sorry didn't check, been a while since I used VS code. Been using PhpStorm

@edalzell `.php_cs.dist` is at root of project

```
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
            ->ignoreDotFiles(true)
            ->ignoreVCS(true)
    );
```

**Comment by yamenarahman** [comment]
@calebporzio It works for me instantly, however how can I set config file to multiple? like '.php_cs' or '.php_cs.dist'
I tried '.php_cs,.php_cs.dist' but not working.

**Comment by coheredigital** [comment]
Same, my error below. Sorry, it makes no sense to me, so no insight on this:
`ERR spawn php-cs-fixer ENOENT: Error: spawn php-cs-fixer ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)`
